In [9]:
import pandas as pd
import numpy as np

In [10]:
my_df = pd.read_excel('WoodInc-sale.xlsx')
my_df

,تاريخ,شماره,کد مشتري,نام مشتري,کد کالا,نام کالا,واحد,مقدار,في,مبلغ,ماليات,مبلغ خالص
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,12750003
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,1299999
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,12500000
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,5850001
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,8000001
...,...,...,...,...,...,...,...,...,...,...,...,...
28269,13991224,98776,1100005,سبزي مهدي ...,1-1-05-056,نئوپان 210*305 خام درجه 1 ...,ورق ...,70.0,3348624,234403680,21096331,255500011
28270,13991225,98826,1102206,محمد جواد حيدري ...,1-1-01-029,ام دي اف 210*366 كد 60 ونگه درجه A ...,ورق ...,2.0,10825688,21651376,1948624,23600000
28271,13991226,98871,1100140,احساني عليرضا ...,1-1-04-157,ملامينه 210*366 كد 70 گردويي تيره درجه A ...,ورق ...,2.0,8440367,16880734,1519266,18400000
28272,13991227,98948,1101709,سيد علي موسوي ...,1-1-05-046,نئوپان 204*260 خام 2% ...,ورق ...,10.0,2935780,29357800,2642202,32000002
28273,13991227,98967,1100004,احسان مولوي ...,1-1-01-776,ام دي اف 183*366 كد 946 نولا اكسترا درجه 1 ...,ورق ...,2.0,15229358,30458716,2741284,33200000

In [11]:
my_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28274 entries, 0 to 28273
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   تاريخ      28274 non-null  int64
 1   شماره      28274 non-null  int64
 2   کد مشتري   28274 non-null  int64
 3   نام مشتري  28274 non-null  str
 4   کد کالا    28274 non-null  str
 5   نام کالا   28274 non-null  str
 6   واحد       28274 non-null  str
 7   مقدار      28274 non-null  float64
 8   في         28274 non-null  int64
 9   مبلغ       28274 non-null  int64
 10  ماليات     28274 non-null  int64
 11  مبلغ خالص  28274 non-null  int64
dtypes: float64(1), int64(7), str(4)
memory usage: 2.6 MB

In [12]:
my_df.describe()

,تاريخ,شماره,کد مشتري,مقدار,في,مبلغ,ماليات,مبلغ خالص
count,2.827400e+04,28274.000000,2.827400e+04,28274.000000,2.827400e+04,2.827400e+04,2.827400e+04,2.827400e+04
mean,1.399068e+07,90681.022600,1.102944e+06,9.174363,3.345904e+06,2.397071e+07,2.154009e+06,2.608744e+07
std,3.271213e+02,4844.246045,1.385136e+05,33.731728,3.471732e+06,7.195606e+07,6.467201e+06,7.832499e+07
min,1.399010e+07,82516.000000,1.100003e+06,0.644000,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
25%,1.399041e+07,86401.250000,1.100013e+06,1.000000,1.449541e+06,3.073394e+06,2.766050e+05,3.349999e+06
50%,1.399063e+07,90570.500000,1.100029e+06,2.000000,2.981651e+06,7.247706e+06,6.522940e+05,7.900000e+06
75%,1.399100e+07,94947.750000,1.101485e+06,6.000000,4.449541e+06,1.862385e+07,1.672018e+06,2.025000e+07
max,1.399123e+07,99014.000000,9.900116e+06,2000.000000,8.899083e+07,3.990826e+09,3.591743e+08,4.350000e+09

In [13]:
my_df.sample(frac=0.05,random_state=40)

,تاريخ,شماره,کد مشتري,نام مشتري,کد کالا,نام کالا,واحد,مقدار,في,مبلغ,ماليات,مبلغ خالص
13304,13990622,90177,1100012,منتشلو ...,1-1-04-376,ملامينه 210*366 كد 137 آنتيك طلائي درجه A ...,ورق ...,1.0,4174312,4174312,375688,4550000
4955,13990322,85265,1100014,غلامي محمد ...,1-1-04-131,ملامينه 210*366 كد 1 سفيد درجه A ...,ورق ...,5.0,3082569,15412845,1387156,16800001
4359,13990313,84915,1100010,حاج ابوئي ...,1-1-02-013,زيرپالتي ام دي اف 210*280 ...,ورق ...,1.0,550459,550459,49541,600000
17238,13990810,92711,1100024,حسين پور احمد ...,1-1-04-558,ملامينه 125*280 كد 326 سامئوتيك ...,ورق ...,1.0,2293578,2293578,206422,2500000
11416,13990528,89062,1101713,حاجي قاسملو رضا ...,1-1-04-747,ملامينه 210*366 كد 140 سفيد متاليك صابوني درجه...,ورق ...,2.0,4449541,8899082,800917,9699999
...,...,...,...,...,...,...,...,...,...,...,...,...
18453,13990826,93432,1100139,غفراني مسعود ...,1-1-04-158,ملامينه 210*366 كد 71 گردويي روشن درجه A ...,ورق ...,6.0,7091743,42550458,3829541,46379999
13976,13990629,90578,1100013,فخار زاده هادي ...,1-1-02-015,زيرپالتي نئوپان 125*280 ...,ورق ...,1.0,275229,275229,24771,300000
4655,13990319,85085,1101182,رضا نيكوگفتار ...,1-1-01-699,ام دي اف 183*366 سفيد صابوني پانو نوين ...,ورق ...,5.0,4541284,22706420,2043578,24749998
8515,13990429,87343,1102541,رمه چي محمود ...,1-1-01-662,ام دي اف 122*280 هايگلاس بيانكو كد 2212 نوين ...,ورق ...,4.0,4568808,18275232,1644771,19920003
16969,13990805,92534,1100011,مصطفي نوحي ...,1-1-04-336,ملامينه 204*260 كد 128 درجه A ...,ورق ...,4.0,2935780,11743120,1056881,12800001

In [14]:
my_df.columns

Index(['تاريخ', 'شماره', 'کد مشتري', 'نام مشتري', 'کد کالا', 'نام کالا',
       'واحد', 'مقدار', 'في', 'مبلغ', 'ماليات', 'مبلغ خالص'],
      dtype='str')

In [15]:
my_df = pd.read_excel('WoodInc-sale.xlsx')
my_df.rename(columns={'تاريخ':'date','کد مشتري' : 'customer_id','نام کالا':'productName','کد کالا':'productID','نام مشتري':'customerName','کد مشتري':'customerID','شماره':'docNumber','مبلغ خالص':'netAmount','ماليات':'tax','مبلغ':'amount','في':'unitPrice','مقدار':'quantity','واحد':'unit'}, inplace=True)
my_df.head()

,date,docNumber,customerID,customerName,productID,productName,unit,quantity,unitPrice,amount,tax,netAmount
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,12750003
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,1299999
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,12500000
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,5850001
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,8000001

In [16]:
my_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28274 entries, 0 to 28273
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          28274 non-null  int64
 1   docNumber     28274 non-null  int64
 2   customerID    28274 non-null  int64
 3   customerName  28274 non-null  str
 4   productID     28274 non-null  str
 5   productName   28274 non-null  str
 6   unit          28274 non-null  str
 7   quantity      28274 non-null  float64
 8   unitPrice     28274 non-null  int64
 9   amount        28274 non-null  int64
 10  tax           28274 non-null  int64
 11  netAmount     28274 non-null  int64
dtypes: float64(1), int64(7), str(4)
memory usage: 2.6 MB

In [17]:
my_df['customerID'] = my_df['customerID'].astype(str)
my_df['docNumber'] = my_df['docNumber'].astype(str)
my_df['date'] = my_df['date'].astype(str)
my_df.drop(columns=['customerID'], inplace=True)
my_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28274 entries, 0 to 28273
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          28274 non-null  str
 1   docNumber     28274 non-null  str
 2   customerName  28274 non-null  str
 3   productID     28274 non-null  str
 4   productName   28274 non-null  str
 5   unit          28274 non-null  str
 6   quantity      28274 non-null  float64
 7   unitPrice     28274 non-null  int64
 8   amount        28274 non-null  int64
 9   tax           28274 non-null  int64
 10  netAmount     28274 non-null  int64
dtypes: float64(1), int64(4), str(6)
memory usage: 2.4 MB

In [18]:
my_df['customerName'].unique()

<StringArray>
['ابوالفضل تام                                                                                                                                                                                            ',
 'احساني عليرضا                                                                                                                                                                                           ',
 'مطهري مهدي                                                                                                                                                                                              ',
 'مصطفي نوحي                                                                                                                                                                                              ',
 'حاج ابوئي                                                                                                                                                                                               ',
 'فرهاد محمدي                                                                                                                                                                                             ',
 'مهدوي هاشم                                                                                                                                                                                              ',
 'رضا ناصري                                                                                                                                                                                               ',
 'رضا نيكوگفتار                                                                                                                                                                                           ',
 'جداخاني                                                                                                                                                                                                 ',
 ...
 'امير حسام بهادري پسند                                                                                                                                                                                   ',
 'صادقي مهدي                                                                                                                                                                                              ',
 'منصوري                                                                                                                                                                                                  ',
 'احسان رياحي فر                                                                                                                                                                                          ',
 'محمد امين بذركار                                                                                                                                                                                        ',
 'حسين كريمي                                                                                                                                                                                              ',
 'محسني خوئي سيدهاشم                                                                                                                                                                                      ',
 'جلال وند                                                                                                                                                                                                ',
 'مهشيد جواديان                                                                                                                                                                                           ',
 'مهدي جوشقاني                                                                                                                                                                                            ']
Length: 681, dtype: str

In [19]:
my_df[my_df['customerName'].str.contains('ابوالفضل', na=False)]
my_df['customerName_clean'] = (
    my_df['customerName']
    .astype(str)
    .str.replace('ي', 'ی')
    .str.replace('ك', 'ک')
    .str.replace('\u200c', ' ')
    .str.replace('\u200f', '')
    .str.replace('\u200e', '')
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [20]:
my_df['customerName_clean'].unique()

<StringArray>
[         'ابوالفضل تام',         'احسانی علیرضا',            'مطهری مهدی',
            'مصطفی نوحی',             'حاج ابوئی',           'فرهاد محمدی',
            'مهدوی هاشم',             'رضا ناصری',         'رضا نیکوگفتار',
               'جداخانی',
 ...
 'امیر حسام بهادری پسند',            'صادقی مهدی',                'منصوری',
        'احسان ریاحی فر',      'محمد امین بذرکار',            'حسین کریمی',
    'محسنی خوئی سیدهاشم',              'جلال وند',         'مهشید جوادیان',
          'مهدی جوشقانی']
Length: 681, dtype: str

In [21]:
my_df[my_df['customerName_clean'] == 'ابوالفضل تام']

,date,docNumber,customerName,productID,productName,unit,quantity,unitPrice,amount,tax,netAmount,customerName_clean
0,13990105,82516,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,12750003,ابوالفضل تام
1,13990105,82516,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,1299999,ابوالفضل تام
2,13990105,82516,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,12500000,ابوالفضل تام
5066,13990324,85332,ابوالفضل تام ...,1-1-02-001,زيرپالتي نئوپان 366*210 ...,ورق ...,20.0,366973,7339460,660551,8000011,ابوالفضل تام
5067,13990324,85332,ابوالفضل تام ...,1-1-05-063,نئوپان 210*366 خام پويا2% ...,ورق ...,10.0,1908257,19082570,1717431,20800001,ابوالفضل تام
5586,13990331,85635,ابوالفضل تام ...,1-1-04-696,ملامينه 90*280 كد 361 سفيد برفي ...,ورق ...,3.0,1009174,3027522,272477,3299999,ابوالفضل تام
8330,13990426,87234,ابوالفضل تام ...,1-1-04-126,ملامينه 210*366 كد 100 سفيد برفي درجه B ...,ورق ...,5.0,3486239,17431195,1568808,19000003,ابوالفضل تام
8404,13990426,87276,ابوالفضل تام ...,1-1-01-575,ام دي اف 8 ميل 122*244 خام خزر كاسپين A ...,ورق ...,20.0,1036697,20733940,1866055,22599995,ابوالفضل تام
8570,13990429,87380,ابوالفضل تام ...,1-1-04-273,ملامينه هايگلاس 210*366 كد 1 سفيد درجه B ...,ورق ...,1.0,3715596,3715596,334404,4050000,ابوالفضل تام
8728,13990431,87481,ابوالفضل تام ...,1-1-04-526,ملامينه 125*280 كد 361 سفيد ...,ورق ...,2.0,1788991,3577982,322018,3900000,ابوالفضل تام
10346,13990516,88444,ابوالفضل تام ...,1-1-04-266,ملامينه هايگلاس 210*366 كد1سفيددرجه A ...,ورق ...,3.0,3990826,11972478,1077523,13050001,ابوالفضل تام
10347,13990516,88444,ابوالفضل تام ...,1-1-01-296,ام دي اف 3 ميل 183*244 سفيد پرينتي واناچاي ...,ورق ...,1.0,1036697,1036697,93303,1130000,ابوالفضل تام
10752,13990522,88698,ابوالفضل تام ...,1-1-04-131,ملامينه 210*366 كد 1 سفيد درجه A ...,ورق ...,3.0,4036697,12110091,1089908,13199999,ابوالفضل تام
10904,13990523,88770,ابوالفضل تام ...,1-1-01-706,ام دي اف 122*280 هايگلاس اينوكس طلائي كد 2330 ...,ورق ...,6.0,7339450,44036700,3963303,48000003,ابوالفضل تام
10905,13990523,88770,ابوالفضل تام ...,1-1-01-293,ام دي اف 183*366 سفيد صابوني مغز تايلندي كد 52...,ورق ...,10.0,6422018,64220180,5779816,69999996,ابوالفضل تام
10906,13990523,88770,ابوالفضل تام ...,1-1-01-296,ام دي اف 3 ميل 183*244 سفيد پرينتي واناچاي ...,ورق ...,6.0,1036697,6220182,559816,6779998,ابوالفضل تام
10907,13990523,88770,ابوالفضل تام ...,1-1-01-165,ام دي اف 122*280 هايگلاس سفيد كد 2210 نوين ...,ورق ...,19.0,6605505,125504595,11295414,136800009,ابوالفضل تام
11943,13990603,89390,ابوالفضل تام ...,1-1-02-009,زيرپالتي ام دي اف 3ميل ...,ورق ...,7.0,137615,963305,86697,1050002,ابوالفضل تام
11944,13990603,89390,ابوالفضل تام ...,1-1-02-009,زيرپالتي ام دي اف 3ميل ...,ورق ...,2.0,1,2,0,2,ابوالفضل تام
12333,13990611,89620,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,2.0,3486239,6972478,627523,7600001,ابوالفضل تام
12334,13990611,89620,ابوالفضل تام ...,1-1-01-461,ام دي اف 210*280 سفيد صابوني درجه 1 كيميا ...,ورق ...,1.0,5779817,5779817,520184,6300001,ابوالفضل تام
12335,13990611,89620,ابوالفضل تام ...,1-1-04-131,ملامينه 210*366 كد 1 سفيد درجه A ...,ورق ...,1.0,4036697,4036697,363303,4400000,ابوالفضل تام

In [22]:
my_df[my_df['customerName_clean'].str.contains(r'\s{2,}', regex=True, na=False)]

Empty DataFrame
Columns: [date, docNumber, customerName, productID, productName, unit, quantity, unitPrice, amount, tax, netAmount, customerName_clean]
Index: []