In [1]:
import pandas as pd
import numpy as np

In [2]:
mydf = pd.read_excel ('TincyCo-V2.xlsx')
mydf

       DB_ID          SKU  Store       Date Unit Sales  Dollar Sales
0      79444  50012011250    312 2014-08-04          3         29.97
1      79445  50012011250    312 2014-08-05          2         19.98
2      79446  50012011250    312 2014-08-06          5         49.95
3      79447  50012011250    312 2014-08-07          3         29.97
4      79448  50012011250    312 2014-08-08          7         69.93
...      ...          ...    ...        ...        ...           ...
19273  82140  50*12011250    632 2005-05-12          2         19.98
19274  82174  50*12011250    632 2005-06-22   -A45%0 4           NaN
19275  82341  50*12011250    632 2006-01-12   -A45%0 2           NaN
19276  82480  50*12011250    632 2006-06-24          2         19.98
19277  82514  50*12011250    632 2006-08-04          2         19.98

[19278 rows x 6 columns]

In [3]:
mydf.columns

Index(['DB_ID', 'SKU', 'Store', 'Date', 'Unit Sales', 'Dollar Sales'], dtype='str')

In [4]:
mydf.info()

<class 'pandas.DataFrame'>
RangeIndex: 19278 entries, 0 to 19277
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DB_ID         19278 non-null  int64
 1   SKU           19278 non-null  object
 2   Store         19278 non-null  int64
 3   Date          19278 non-null  datetime64[us]
 4   Unit Sales    19017 non-null  object
 5   Dollar Sales  18909 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(2), object(2)
memory usage: 903.8+ KB

In [5]:
mydf.isna().sum()

DB_ID             0
SKU               0
Store             0
Date              0
Unit Sales      261
Dollar Sales    369
dtype: int64

In [6]:
dollar_mean = mydf['Dollar Sales'].mean()
dollar_mean

np.float64(673.7160621926067)

In [7]:
mydf['Dollar Sales Mean Fill'] = mydf['Dollar Sales'].fillna(dollar_mean)

In [8]:
mydf[['Dollar Sales','Dollar Sales Mean Fill']].isna().sum()

Dollar Sales              369
Dollar Sales Mean Fill      0
dtype: int64

In [9]:
mydf['Date'] = pd.to_datetime(mydf['Date'])

In [10]:
mydf['Date'].dtype

dtype('<M8[us]')

In [11]:
mydf['year'] = mydf['Date'].dt.year
mydf[['Date','year']].head()

        Date  year
0 2014-08-04  2014
1 2014-08-05  2014
2 2014-08-06  2014
3 2014-08-07  2014
4 2014-08-08  2014

In [12]:
year_sales = mydf.groupby('year').agg(
    total_dollar_sales = ('Dollar Sales Mean Fill' , 'sum')
).reset_index()
year_sales

   year  total_dollar_sales
0  2004        1.518662e+06
1  2005        4.364798e+06
2  2006        3.080955e+06
3  2014        1.244555e+06
4  2015        1.034070e+06
5  2016        1.744859e+06

In [13]:
mydf['quarter'] = mydf['Date'] .dt.quarter
mydf[['Date','year','quarter']].head()

        Date  year  quarter
0 2014-08-04  2014        3
1 2014-08-05  2014        3
2 2014-08-06  2014        3
3 2014-08-07  2014        3
4 2014-08-08  2014        3

In [14]:
quarter_sales = mydf.groupby (
    ['year' ,'quarter']
).agg(
    total_dollar_sales = ('Dollar Sales Mean Fill' , 'sum')
    
).reset_index()
quarter_sales

    year  quarter  total_dollar_sales
0   2004        3        3.692017e+05
1   2004        4        1.149460e+06
2   2005        1        2.039395e+06
3   2005        2        1.485252e+05
4   2005        3        1.267740e+06
5   2005        4        9.091376e+05
6   2006        1        1.798705e+06
7   2006        2        2.704667e+05
8   2006        3        1.011783e+06
9   2014        3        3.138196e+05
10  2014        4        9.307350e+05
11  2015        1        1.280084e+05
12  2015        2        5.297651e+05
13  2015        3        3.808592e+04
14  2015        4        3.382103e+05
15  2016        1        1.152487e+06
16  2016        2        5.931684e+04
17  2016        3        5.330547e+05

In [15]:
mydf['month'] = mydf ['Date'].dt.month
month_sales = mydf.groupby (
    ['year' ,'month']
).agg(
    total_dollar_sales = ('Dollar Sales Mean Fill','sum')
).reset_index()
month_sales

    year  month  total_dollar_sales
0   2004      8        2.873687e+04
1   2004      9        3.404648e+05
2   2004     10        4.883479e+04
3   2004     11        1.471814e+05
4   2004     12        9.534443e+05
5   2005      1        1.047417e+06
6   2005      2        4.694247e+04
7   2005      3        9.450354e+05
8   2005      4        4.760590e+04
9   2005      5        4.792650e+04
10  2005      6        5.299279e+04
11  2005      7        4.777884e+04
12  2005      8        6.535979e+05
13  2005      9        5.663633e+05
14  2005     10        2.676562e+05
15  2005     11        6.512027e+04
16  2005     12        5.763611e+05
17  2006      1        1.462284e+06
18  2006      2        6.535019e+04
19  2006      3        2.710707e+05
20  2006      4        7.051095e+04
21  2006      5        1.257716e+05
22  2006      6        7.418417e+04
23  2006      7        5.748208e+05
24  2006      8        4.369624e+05
25  2014      8        3.047395e+05
26  2014      9        9.080084e+03
27  2014     10        9.962590e+03
28  2014     11        9.071047e+05
29  2014     12        1.366766e+04
30  2015      1        1.005089e+04
31  2015      2        1.066951e+05
32  2015      3        1.126249e+04
33  2015      4        2.089823e+05
34  2015      5        1.131631e+04
35  2015      6        3.094666e+05
36  2015      7        1.090755e+04
37  2015      8        1.262278e+04
38  2015      9        1.455559e+04
39  2015     10        3.125350e+05
40  2015     11        1.370175e+04
41  2015     12        1.197358e+04
42  2016      1        4.195643e+05
43  2016      2        7.155569e+05
44  2016      3        1.736594e+04
45  2016      4        1.636055e+04
46  2016      5        2.507213e+04
47  2016      6        1.788416e+04
48  2016      7        5.201231e+05
49  2016      8        1.293164e+04

In [16]:
mydf['week'] = mydf ['Date'].dt.isocalendar().week

In [17]:
week_sales = mydf.groupby (
    ['year' ,'week']
).agg(
    total_dollar_sales = ('Dollar Sales Mean Fill','sum')
).reset_index()
week_sales

     year  week  total_dollar_sales
0    2004    32         1904.160000
1    2004    33         3969.588187
2    2004    34         7487.766062
3    2004    35        12514.010311
4    2004    36         8409.356062
..    ...   ...                 ...
212  2016    30         5363.176062
213  2016    31         3706.436062
214  2016    32         3890.050000
215  2016    33         5335.150000
216  2016    53         4271.112124

[217 rows x 3 columns]

In [18]:
mydf ['day_date'] = mydf['Date'].dt.date

In [19]:
day_sales = mydf.groupby (
    'day_date'
).agg(
    total_dollar_sales = ('Dollar Sales Mean Fill','sum')
).reset_index()
day_sales

        day_date  total_dollar_sales
0     2004-08-02              531.66
1     2004-08-03              185.78
2     2004-08-04              238.72
3     2004-08-05              443.65
4     2004-08-06              232.70
...          ...                 ...
1283  2016-08-16              517.63
1284  2016-08-17             1144.22
1285  2016-08-18             1056.22
1286  2016-08-19             1110.16
1287  2016-08-20             1165.08

[1288 rows x 2 columns]

In [20]:
sku_month_sales = mydf.groupby (
    ['year' , 'month' ,'SKU']).agg(
        total_dollar_sales = ('Dollar Sales Mean Fill','sum')
    
    ).reset_index()
    
sku_month_sales

     year  month          SKU  total_dollar_sales
0    2004      8   7312455520          457.810000
1    2004      8   7312455530          449.800000
2    2004      8   8000451112         8016.390000
3    2004      8   8000520021         5610.000000
4    2004      8  50012011240         2819.346062
..    ...    ...          ...                 ...
368  2016      8   8000451112         9521.670000
369  2016      8   8000520021          629.370000
370  2016      8  50012011240          753.616062
371  2016      8  50012011250          209.790000
372  2016      8  50012011341           49.900000

[373 rows x 4 columns]

In [21]:
sku_dollar_mean =mydf.groupby('SKU').agg(
    sku_mean_dollar_sales = ('Dollar Sales','mean')
).reset_index()
sku_dollar_mean.head()

           SKU  sku_mean_dollar_sales
0   7312455520              46.529490
1   7312455530              51.522585
2   8000451112             220.494400
3   8000520021              66.505475
4  50012011240              20.092586

In [23]:
mydf = pd.merge(
    left= mydf,
    right= sku_dollar_mean,
    on='SKU',
    how='left'
)
mydf

,DB_ID,SKU,Store,Date,Unit Sales,Dollar Sales,Dollar Sales Mean Fill,year,quarter,month,week,day_date,sku_mean_dollar_sales
0,79444,50012011250,312,2014-08-04,3,29.97,29.970000,2014,3,8,32,2014-08-04,3858.255752
1,79445,50012011250,312,2014-08-05,2,19.98,19.980000,2014,3,8,32,2014-08-05,3858.255752
2,79446,50012011250,312,2014-08-06,5,49.95,49.950000,2014,3,8,32,2014-08-06,3858.255752
3,79447,50012011250,312,2014-08-07,3,29.97,29.970000,2014,3,8,32,2014-08-07,3858.255752
4,79448,50012011250,312,2014-08-08,7,69.93,69.930000,2014,3,8,32,2014-08-08,3858.255752
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19273,82140,50*12011250,632,2005-05-12,2,19.98,19.980000,2005,2,5,19,2005-05-12,55.324286
19274,82174,50*12011250,632,2005-06-22,-A45%0 4,NaN,673.716062,2005,2,6,25,2005-06-22,55.324286
19275,82341,50*12011250,632,2006-01-12,-A45%0 2,NaN,673.716062,2006,1,1,2,2006-01-12,55.324286
19276,82480,50*12011250,632,2006-06-24,2,19.98,19.980000,2006,2,6,25,2006-06-24,55.324286
19277,82514,50*12011250,632,2006-08-04,2,19.98,19.980000,2006,3,8,31,2006-08-04,55.324286

In [25]:
mydf[ 'Dollar Sales SKU Mean Fill'] = np.where(
    mydf['Dollar Sales'].isna(),
    mydf['sku_mean_dollar_sales'],
    mydf['Dollar Sales']
)

mydf

,DB_ID,SKU,Store,Date,Unit Sales,Dollar Sales,Dollar Sales Mean Fill,year,quarter,month,week,day_date,sku_mean_dollar_sales,Dollar Sales SKU Mean Fill
0,79444,50012011250,312,2014-08-04,3,29.97,29.970000,2014,3,8,32,2014-08-04,3858.255752,29.970000
1,79445,50012011250,312,2014-08-05,2,19.98,19.980000,2014,3,8,32,2014-08-05,3858.255752,19.980000
2,79446,50012011250,312,2014-08-06,5,49.95,49.950000,2014,3,8,32,2014-08-06,3858.255752,49.950000
3,79447,50012011250,312,2014-08-07,3,29.97,29.970000,2014,3,8,32,2014-08-07,3858.255752,29.970000
4,79448,50012011250,312,2014-08-08,7,69.93,69.930000,2014,3,8,32,2014-08-08,3858.255752,69.930000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19273,82140,50*12011250,632,2005-05-12,2,19.98,19.980000,2005,2,5,19,2005-05-12,55.324286,19.980000
19274,82174,50*12011250,632,2005-06-22,-A45%0 4,NaN,673.716062,2005,2,6,25,2005-06-22,55.324286,55.324286
19275,82341,50*12011250,632,2006-01-12,-A45%0 2,NaN,673.716062,2006,1,1,2,2006-01-12,55.324286,55.324286
19276,82480,50*12011250,632,2006-06-24,2,19.98,19.980000,2006,2,6,25,2006-06-24,55.324286,19.980000
19277,82514,50*12011250,632,2006-08-04,2,19.98,19.980000,2006,3,8,31,2006-08-04,55.324286,19.980000

In [26]:
mydf[['Dollar Sales', 'Dollar Sales SKU Mean Fill']].isna().sum()

Dollar Sales                  369
Dollar Sales SKU Mean Fill      0
dtype: int64