In [2]:
import pandas as pd
import numpy as np

In [3]:
mydf = pd.read_excel('WoodInc-sale.xlsx')
mydf.head()

,تاريخ,شماره,کد مشتري,نام مشتري,کد کالا,نام کالا,واحد,مقدار,في,مبلغ,ماليات,مبلغ خالص
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,12750003
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,1299999
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,12500000
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,5850001
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,8000001

In [4]:
mydf.columns

Index(['تاريخ', 'شماره', 'کد مشتري', 'نام مشتري', 'کد کالا', 'نام کالا',
       'واحد', 'مقدار', 'في', 'مبلغ', 'ماليات', 'مبلغ خالص'],
      dtype='str')

In [5]:
Customer_group =mydf.groupby( ['نام مشتري','کد مشتري'] ).agg(total_buy=('مبلغ خالص','sum')).reset_index()
Customer_group.head()

                                           نام مشتري  کد مشتري   total_buy
0  آزادي اعتماد                                  ...   1101081  4566910284
1  آسيابان سعيد                                  ...   1101534  1368349916
2  آقا زيارتي علي                                ...   1101730  7648139841
3  آقا محمدي سعيد                                ...   1100044  5678698961
4  آقاخاني احمد                                  ...   1100293   283499975

In [14]:
my_df = pd.read_excel('WoodInc-sale.xlsx')
my_df.rename(columns={'تاريخ':'date','کد مشتري' : 'customer_id','نام کالا':'productName','کد کالا':'productID','نام مشتري':'customerName','کد مشتري':'customerID','شماره':'docNumber','مبلغ خالص':'netAmount','ماليات':'tax','مبلغ':'amount','في':'unitPrice','مقدار':'quantity','واحد':'unit'}, inplace=True)
my_df.head()

,date,docNumber,customerID,customerName,productID,productName,unit,quantity,unitPrice,amount,tax,netAmount
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,12750003
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,1299999
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,12500000
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,5850001
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,8000001

In [7]:
Coustomer_gp= mydf.groupby(['customerName','customerID']).agg(totalbuy=('netAmount','sum')).reset_index()
Coustomer_gp.head()

                                        customerName  customerID    totalbuy
0  آزادي اعتماد                                  ...     1101081  4566910284
1  آسيابان سعيد                                  ...     1101534  1368349916
2  آقا زيارتي علي                                ...     1101730  7648139841
3  آقا محمدي سعيد                                ...     1100044  5678698961
4  آقاخاني احمد                                  ...     1100293   283499975

In [ ]:
Customer_gp = Customer_gp.sort_values(by='totalbuy',ascending=False).head(n=3)
Customer_gp.head(n=3)

,customerName,customerID,totalbuy
441,فخار زاده هادي ...,1100013,32880404684
573,مصطفي نوحي ...,1100011,30843447536
548,مختاري احمد ...,1101781,27524560602

In [9]:
totalsales =mydf['netAmount'].sum()
totalsales

np.int64(737596180097)

In [10]:
topcustomer= Coustomer_gp.head(n=3)
topcustomer

,customerName,customerID,totalbuy
441,فخار زاده هادي ...,1100013,32880404684
573,مصطفي نوحي ...,1100011,30843447536
548,مختاري احمد ...,1101781,27524560602

In [11]:
topcustomer ['share']=(topcustomer['totalbuy'] / totalsales)*100
topcustomer

,customerName,customerID,totalbuy,share
441,فخار زاده هادي ...,1100013,32880404684,4.457779
573,مصطفي نوحي ...,1100011,30843447536,4.181617
548,مختاري احمد ...,1101781,27524560602,3.731657

In [12]:
productgp= mydf.groupby(['productID' ,'productName']).agg(totalbuy=('netAmount','sum')).reset_index()
productgp=productgp.sort_values(by="totalbuy",ascending=False)

top_product =productgp.head(n=3)
top_product['share'] =(top_product['totalbuy']/totalsales)*100

top_product

,productID,productName,totalbuy,share
307,1-1-04-131,ملامينه 210*366 كد 1 سفيد درجه A ...,50538108597,6.851731
99,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,34103627703,4.623618
419,1-1-04-526,ملامينه 125*280 كد 361 سفيد ...,28459240929,3.858377